i2t-spike/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,
             path: '',
             path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                 registration: 'signup'
             },
             controllers: {
                 sessions: 'sessions',
                 registrations: 'registrations'
             }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/game(/:id)', to: 'game#game', as: 'game'
  get '/game/round/:id', to: 'game#round', as: 'round'
  get '/win', to: 'welcome#win', as: 'win'

  namespace :api do
    resources :games
    resources :rounds
  end
  root 'welcome#index'
end

i2t-spike/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

i2t-spike/app/models/game.rb
class Game < ApplicationRecord
  after_initialize :set_game_seed

  def round
    @round ||= 1
  end

  def round=(round_number)
    @round = round_number
  end

  def term
    @term = Term.all.sort_by{ rng }.first(rounds)[round - 1].term
  end

  def rounds
    [Term.all.count, 10].min # max of 10 rounds
  end

  def images
    @@game_images ||= YAML.load(File.open('config/initializers/game_images.yaml'))
    @@game_images['terms'][term] || ImageSearchService.new(term).call
  end

  private

  def rng
    Random.new(self.seed.to_i)
  end

  def set_game_seed
    self.seed = Random.new_seed.to_s
  end
end

i2t-spike/app/models/jwt_blacklist.rb
class JWTBlacklist < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Blacklist

  self.table_name = 'jwt_blacklist'
end

i2t-spike/app/models/term.rb
class Term < ApplicationRecord
end

i2t-spike/app/models/user.rb
class User < ApplicationRecord
  before_save :set_jti

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: JWTBlacklist

  private

  def set_jti
    self.jti ||= SecureRandom.uuid
  end
end

i2t-spike/app/controllers/api/base_api_controller.rb
class Api::BaseApiController < ApplicationController
end

i2t-spike/app/controllers/api/games_controller.rb
module Api
  class GamesController < BaseApiController
    def index
      render json: Game.all.limit(10)
    end

    def show
      render json: Game.find(params[:id])
    end
  end
end

i2t-spike/app/controllers/api/games_controller_controller.rb
class Api::GamesControllerController < ApplicationController
end

i2t-spike/app/controllers/api/rounds_controller.rb
module Api
  class RoundsController < BaseApiController
    def show
      rounds   = 3
      seed_str = params[:seed] || Random.new_seed.to_s
      round     = params[:id].to_i
      term = Term
          .all
          .sort_by{ random_number_generator(seed_str) }
          .first(rounds)[round - 1]
          &.term
      images = ImageSearchService
          .new(term)
          .call
          .shuffle
          .first(9)
          .each_with_index
          .map { |image, index| { id: index, src: image } }
      render json: {
          round: round,
          seed: seed_str,
          term: term,
          images: images
      }
    end

    private

    def random_number_generator(seed_str)
      Random.new(seed_str.to_i)
    end
  end
end

i2t-spike/app/controllers/game_controller.rb
class GameController < ApplicationController
  def game
    if params.has_key?(:id)
      @game = Game.find(params[:id])
    else
      @game = Game.new
      @game.save
    end
    @game.round = params[:round].to_i if params.has_key?(:round)
  end

  def round
    @game = Game.find(params[:id])
    @game.round = params[:round].to_i if params.has_key?(:round)
    if params[:term]
      if params[:term] == @game.term
        flash.clear
        flash[:success] = "#{params[:term].inspect} is correct"
        if @game.round >= @game.rounds
          redirect_to win_path
        else
          redirect_to game_path(@game.id, round: @game.round + 1)
        end
      else
        flash.clear
        flash[:warn] = "#{params[:term].inspect} is NOT correct try again"
      end
    end
    @images = @game.images
  end
end

i2t-spike/app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  respond_to :json

  private

  def respond_with(resource, _opts = {})
    render json: resource
  end

  def respond_to_on_destroy
    head :no_content
  end
end

i2t-spike/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def win
  end
end

i2t-spike/app/helpers/welcome_helper.rb
module WelcomeHelper
end

i2t-spike/app/views/game/game.html.erb
<h1>Play</h1>

<%= link_to 'Start again', root_path %>

<form action="<%= round_path(@game.id) %>">
  <input type="hidden" name="round" value="<%= @game.round %>" />
  <input type="submit" name="Submit" value="<%= "Round #{@game.round} of #{@game.rounds}" %>"/>
</form>

i2t-spike/app/views/game/round.html.erb
<h1>Play - <%= "Round #{@game.round} of #{@game.rounds}" %></h1>

<%= link_to 'Start again', root_path %>

<form action="<%= round_path(@game.id) %>">
  <input type="hidden" name="round" value="<%= @game.round %>" />
  <input type="text" name="term" placeholder="guess?" />
  <input type="submit" name="Submit" />
</form>

<% @images && @images.each do |image| %>
  <img src="<%= image %>">
<% end %>

i2t-spike/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>I2tSpike</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

i2t-spike/app/views/welcome/index.html.erb
<h1>Images 2 text</h1>

<%= link_to 'Start the game', game_path %>

i2t-spike/app/views/welcome/win.html.erb
<h1>WIN</h1>

<%= link_to 'Start the game', root_path %>